// Shared kernel types for every payments-platform gRPC service.
//
// This file is the protobuf mirror of `internal/domain/shared`: identifiers, Money,
// tenancy context, pagination and the error model. It is deliberately tiny. Anything
// added here becomes a dependency of every context, so a change requires review from
// every context owner.
//
// Source of truth: docs/spec/00-design-baseline.md sections 6, 7, 14, 19, 20.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: payments/v1/common.proto

package paymentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Classification of the acting principal, mirrored into the audit trail.
type ActorType int32

const (
	ActorType_ACTOR_TYPE_UNSPECIFIED ActorType = 0
	// A human operator authenticated through the console.
	ActorType_ACTOR_TYPE_USER ActorType = 1
	// A tenant's machine client authenticated by OAuth2 client credentials.
	ActorType_ACTOR_TYPE_API_CLIENT ActorType = 2
	// One of our own workloads authenticated by mTLS/SPIFFE.
	ActorType_ACTOR_TYPE_SYSTEM ActorType = 3
	// The workflow engine acting on a checkpointed step.
	ActorType_ACTOR_TYPE_WORKFLOW ActorType = 4
)

// Enum value maps for ActorType.
var (
	ActorType_name = map[int32]string{
		0: "ACTOR_TYPE_UNSPECIFIED",
		1: "ACTOR_TYPE_USER",
		2: "ACTOR_TYPE_API_CLIENT",
		3: "ACTOR_TYPE_SYSTEM",
		4: "ACTOR_TYPE_WORKFLOW",
	}
	ActorType_value = map[string]int32{
		"ACTOR_TYPE_UNSPECIFIED": 0,
		"ACTOR_TYPE_USER":        1,
		"ACTOR_TYPE_API_CLIENT":  2,
		"ACTOR_TYPE_SYSTEM":      3,
		"ACTOR_TYPE_WORKFLOW":    4,
	}
)

func (x ActorType) Enum() *ActorType {
	p := new(ActorType)
	*p = x
	return p
}

func (x ActorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorType) Descriptor() protoreflect.EnumDescriptor {
	return file_payments_v1_common_proto_enumTypes[0].Descriptor()
}

func (ActorType) Type() protoreflect.EnumType {
	return &file_payments_v1_common_proto_enumTypes[0]
}

func (x ActorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorType.Descriptor instead.
func (ActorType) EnumDescriptor() ([]byte, []int) {
	return file_payments_v1_common_proto_rawDescGZIP(), []int{0}
}

// Deployment environment. A sandbox artifact never certifies a production resource.
type Environment int32

const (
	Environment_ENVIRONMENT_UNSPECIFIED Environment = 0
	Environment_ENVIRONMENT_SANDBOX     Environment = 1
	Environment_ENVIRONMENT_PRODUCTION  Environment = 2
)

// Enum value maps for Environment.
var (
	Environment_name = map[int32]string{
		0: "ENVIRONMENT_UNSPECIFIED",
		1: "ENVIRONMENT_SANDBOX",
		2: "ENVIRONMENT_PRODUCTION",
	}
	Environment_value = map[string]int32{
		"ENVIRONMENT_UNSPECIFIED": 0,
		"ENVIRONMENT_SANDBOX":     1,
		"ENVIRONMENT_PRODUCTION":  2,
	}
)

func (x Environment) Enum() *Environment {
	p := new(Environment)
	*p = x
	return p
}

func (x Environment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Environment) Descriptor() protoreflect.EnumDescriptor {
	return file_payments_v1_common_proto_enumTypes[1].Descriptor()
}

func (Environment) Type() protoreflect.EnumType {
	return &file_payments_v1_common_proto_enumTypes[1]
}

func (x Environment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Environment.Descriptor instead.
func (Environment) EnumDescriptor() ([]byte, []int) {
	return file_payments_v1_common_proto_rawDescGZIP(), []int{1}
}

// Coarse classification of a failure, driving gRPC code, retryability and alerting.
//
// This mirrors the HTTP error model exactly: one catalogue, two transports.
type ErrorCategory int32

const (
	ErrorCategory_ERROR_CATEGORY_UNSPECIFIED ErrorCategory = 0
	// Malformed or schema-invalid input. gRPC INVALID_ARGUMENT. Not retryable.
	ErrorCategory_ERROR_CATEGORY_VALIDATION ErrorCategory = 1
	// Missing or invalid credentials. gRPC UNAUTHENTICATED. Not retryable.
	ErrorCategory_ERROR_CATEGORY_AUTHENTICATION ErrorCategory = 2
	// Authenticated but not permitted. gRPC PERMISSION_DENIED. Not retryable.
	ErrorCategory_ERROR_CATEGORY_AUTHORIZATION ErrorCategory = 3
	// No such resource within the caller's tenant. gRPC NOT_FOUND. Not retryable.
	ErrorCategory_ERROR_CATEGORY_NOT_FOUND ErrorCategory = 4
	// State conflict. gRPC ABORTED or FAILED_PRECONDITION. Retryable only for an
	// in-flight idempotent duplicate.
	ErrorCategory_ERROR_CATEGORY_CONFLICT ErrorCategory = 5
	// A business rule refused the operation. gRPC FAILED_PRECONDITION. Not retryable.
	ErrorCategory_ERROR_CATEGORY_BUSINESS_RULE ErrorCategory = 6
	// Rate limit or bulkhead. gRPC RESOURCE_EXHAUSTED. Retryable after the stated delay.
	ErrorCategory_ERROR_CATEGORY_RATE_LIMIT ErrorCategory = 7
	// A gateway failed or violated its contract. gRPC UNAVAILABLE. Retryable unless the
	// decline was hard.
	ErrorCategory_ERROR_CATEGORY_GATEWAY ErrorCategory = 8
	// A call timed out with an AMBIGUOUS outcome. gRPC DEADLINE_EXCEEDED. Retryability
	// is not a boolean here - see the timeout rule in payment.proto.
	ErrorCategory_ERROR_CATEGORY_TIMEOUT ErrorCategory = 9
	// Infrastructure is unavailable and we fail closed. gRPC UNAVAILABLE. Retryable.
	ErrorCategory_ERROR_CATEGORY_INFRASTRUCTURE ErrorCategory = 10
	// An unexpected internal fault. gRPC INTERNAL. Not retryable; it pages.
	ErrorCategory_ERROR_CATEGORY_INTERNAL ErrorCategory = 11
)

// Enum value maps for ErrorCategory.
var (
	ErrorCategory_name = map[int32]string{
		0:  "ERROR_CATEGORY_UNSPECIFIED",
		1:  "ERROR_CATEGORY_VALIDATION",
		2:  "ERROR_CATEGORY_AUTHENTICATION",
		3:  "ERROR_CATEGORY_AUTHORIZATION",
		4:  "ERROR_CATEGORY_NOT_FOUND",
		5:  "ERROR_CATEGORY_CONFLICT",
		6:  "ERROR_CATEGORY_BUSINESS_RULE",
		7:  "ERROR_CATEGORY_RATE_LIMIT",
		8:  "ERROR_CATEGORY_GATEWAY",
		9:  "ERROR_CATEGORY_TIMEOUT",
		10: "ERROR_CATEGORY_INFRASTRUCTURE",
		11: "ERROR_CATEGORY_INTERNAL",
	}
	ErrorCategory_value = map[string]int32{
		"ERROR_CATEGORY_UNSPECIFIED":    0,
		"ERROR_CATEGORY_VALIDATION":     1,
		"ERROR_CATEGORY_AUTHENTICATION": 2,
		"ERROR_CATEGORY_AUTHORIZATION":  3,
		"ERROR_CATEGORY_NOT_FOUND":      4,
		"ERROR_CATEGORY_CONFLICT":       5,
		"ERROR_CATEGORY_BUSINESS_RULE":  6,
		"ERROR_CATEGORY_RATE_LIMIT":     7,
		"ERROR_CATEGORY_GATEWAY":        8,
		"ERROR_CATEGORY_TIMEOUT":        9,
		"ERROR_CATEGORY_INFRASTRUCTURE": 10,
		"ERROR_CATEGORY_INTERNAL":       11,
	}
)

func (x ErrorCategory) Enum() *ErrorCategory {
	p := new(ErrorCategory)
	*p = x
	return p
}

func (x ErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_payments_v1_common_proto_enumTypes[2].Descriptor()
}

func (ErrorCategory) Type() protoreflect.EnumType {
	return &file_payments_v1_common_proto_enumTypes[2]
}

func (x ErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCategory.Descriptor instead.
func (ErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_payments_v1_common_proto_rawDescGZIP(), []int{2}
}

// Money is an amount in the currency's MINOR units plus its ISO 4217 code.
//
// There is no floating point anywhere in the money path: `double` cannot represent
// 0.10, and a decimal string invites the parsing bug it was meant to avoid.
// Arithmetic across differing currencies is an error, never a silent conversion.
// Splitting uses largest-remainder allocation so the parts always sum to the whole.
type Money struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount in minor units of `currency` (cents, pence, fils). Integer, always.
	// The minor-unit exponent comes from an embedded ISO 4217 table (USD=2, JPY=0,
	// BHD=3, CLF=4) and is never inferred from the value.
	Amount int64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// ISO 4217 alphabetic code, uppercase, e.g. "USD".
	Currency      string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_payments_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_payments_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// Who is calling, on whose behalf, and under which trace.
//
// The tenant is derived EXCLUSIVELY from the authenticated principal. A tenant
// identifier that disagrees with the caller's credential is a security event, not a
// parameter: the isolation guard rejects it with PERMISSION_DENIED / TENANT_MISMATCH.
// An mTLS mesh identity is not tenant-scoped and can never satisfy a tenant-scoped
// read on its own - it must propagate this context explicitly.
type TenantContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `ten_` + ULID. Required on every tenant-scoped RPC.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// `mrc_` + ULID. Required on merchant-scoped RPCs, empty on platform-scoped ones.
	MerchantId string `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	// The acting principal: `cli_`/`usr_`/`system:<component>`/SPIFFE ID.
	PrincipalId string `protobuf:"bytes,3,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	// What kind of actor `principal_id` names. Drives audit classification.
	ActorType ActorType `protobuf:"varint,4,opt,name=actor_type,json=actorType,proto3,enum=payments.v1.ActorType" json:"actor_type,omitempty"`
	// `req_` + ULID. Constant across the entire causal fan-out of one API call, so one
	// request's full consequences - payments, attempts, events, audit records - are one
	// query.
	CorrelationId string `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// W3C trace context: `00-<32 hex trace-id>-<16 hex span-id>-<2 hex flags>`.
	Traceparent string `protobuf:"bytes,6,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	// The originating HTTP request identifier, echoed to the client as X-Request-Id.
	RequestId string `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Scopes granted to the caller, for defence-in-depth checks inside a service that
	// was reached through another service. Never used to GRANT - only to deny.
	Scopes        []string `protobuf:"bytes,8,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantContext) Reset() {
	*x = TenantContext{}
	mi := &file_payments_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantContext) ProtoMessage() {}

func (x *TenantContext) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantContext.ProtoReflect.Descriptor instead.
func (*TenantContext) Descriptor() ([]byte, []int) {
	return file_payments_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *TenantContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantContext) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *TenantContext) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *TenantContext) GetActorType() ActorType {
	if x != nil {
		return x.ActorType
	}
	return ActorType_ACTOR_TYPE_UNSPECIFIED
}

func (x *TenantContext) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TenantContext) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *TenantContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TenantContext) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

// Opaque-cursor pagination request.
//
// There is no offset pagination anywhere in this platform: offsets are unstable under
// concurrent writes and silently skip or duplicate rows on a busy list.
type PageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum items to return. Zero means the server default (50). Capped at 200.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque continuation token from a previous PageResponse. Signed, tied to the tenant
	// and to the exact filter set of the originating request, and valid for 24 hours.
	// Callers must not construct, parse or reuse one across different filters.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_payments_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_payments_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Opaque-cursor pagination response.
type PageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for the next page. Empty when this is the last page.
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Best-effort total, populated only where it can be produced without a second scan.
	// Zero means "not computed", never "no rows" - use an empty result set for that.
	ApproximateTotal int64 `protobuf:"varint,2,opt,name=approximate_total,json=approximateTotal,proto3" json:"approximate_total,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_payments_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_payments_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *PageResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *PageResponse) GetApproximateTotal() int64 {
	if x != nil {
		return x.ApproximateTotal
	}
	return 0
}

// The platform error model, carried in `google.rpc.Status.details` and mirrored 1:1
// by the RFC 9457 problem document on the REST surface.
//
// `retryable` is a machine-readable contract that client SDKs, the workflow engine and
// the outbox relay branch on. It is not advisory prose.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable code from api/errors/catalog.yaml, e.g. "REFUND_EXCEEDS_CAPTURED". This,
	// not the message, is what callers branch on.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Coarse category. Determines the gRPC status code.
	Category ErrorCategory `protobuf:"varint,2,opt,name=category,proto3,enum=payments.v1.ErrorCategory" json:"category,omitempty"`
	// Human-readable, instance-specific explanation. Contains identifiers and amounts;
	// never cardholder data, credentials or personal data.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Whether retrying the identical request with the same idempotency key can succeed.
	Retryable bool `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// Echo of TenantContext.request_id, so a failure can be traced from a client log.
	RequestId string `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// W3C trace id (32 hex characters) of the failing request.
	TraceId string `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Field-level breakdown. Present whenever the failure is attributable to specific
	// inputs; absent for infrastructure failures.
	Details []*ErrorDetail `protobuf:"bytes,7,rep,name=details,proto3" json:"details,omitempty"`
	// Documentation anchor for `code`, including remediation.
	DocsUrl string `protobuf:"bytes,8,opt,name=docs_url,json=docsUrl,proto3" json:"docs_url,omitempty"`
	// How long to wait before retrying, when `retryable` is true and a delay applies.
	RetryAfterSeconds int32 `protobuf:"varint,9,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_payments_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_payments_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetCategory() ErrorCategory {
	if x != nil {
		return x.Category
	}
	return ErrorCategory_ERROR_CATEGORY_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *Error) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Error) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Error) GetDetails() []*ErrorDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Error) GetDocsUrl() string {
	if x != nil {
		return x.DocsUrl
	}
	return ""
}

func (x *Error) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

// One attributable cause within an Error.
type ErrorDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dotted path to the offending field, where one applies.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Stable sub-code, e.g. "EXCEEDS_REFUNDABLE".
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable explanation. Never contains cardholder data or secrets.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Validation-plane rule identifier, e.g. "L5.AMOUNT_WITHIN_MERCHANT_LIMIT". Every
	// rule id is documented with its meaning and remediation, and CI fails the build if
	// one is not.
	RuleId        string `protobuf:"bytes,4,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_payments_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_payments_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

// Idempotency parameters for an unsafe RPC.
//
// The scope is (tenant_id, merchant_id, method, path_template, key). A SHA-256
// fingerprint of the canonicalized request is stored with the key: the same key with a
// different request is IDEMPOTENCY_KEY_REUSED, which is the check that catches a
// client reusing one key for two different operations. A concurrent duplicate while
// the first is still executing is IDEMPOTENT_REQUEST_IN_PROGRESS with a retry delay -
// we never block a caller on another process's lease, and we never process twice.
type IdempotencyOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-supplied opaque key, 1-255 characters. Generate it BEFORE the first attempt
	// and reuse it across every retry of that logical operation.
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdempotencyOptions) Reset() {
	*x = IdempotencyOptions{}
	mi := &file_payments_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotencyOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotencyOptions) ProtoMessage() {}

func (x *IdempotencyOptions) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotencyOptions.ProtoReflect.Descriptor instead.
func (*IdempotencyOptions) Descriptor() ([]byte, []int) {
	return file_payments_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *IdempotencyOptions) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Result metadata returned alongside an idempotent operation's response.
type IdempotencyResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when this response was replayed from a stored record rather than produced by
	// executing the operation again.
	Replayed bool `protobuf:"varint,1,opt,name=replayed,proto3" json:"replayed,omitempty"`
	// When the stored record was first completed. Useful for diagnosing a client that
	// believes it has never received a response.
	FirstCompletedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=first_completed_at,json=firstCompletedAt,proto3" json:"first_completed_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IdempotencyResult) Reset() {
	*x = IdempotencyResult{}
	mi := &file_payments_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotencyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotencyResult) ProtoMessage() {}

func (x *IdempotencyResult) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotencyResult.ProtoReflect.Descriptor instead.
func (*IdempotencyResult) Descriptor() ([]byte, []int) {
	return file_payments_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *IdempotencyResult) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

func (x *IdempotencyResult) GetFirstCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstCompletedAt
	}
	return nil
}

// A resource's optimistic-concurrency token, mirrored by the HTTP ETag.
//
// Every aggregate write is version-checked. A stale version loses and must re-read,
// re-apply and retry; it is never silently merged.
type Precondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The version the caller believes is current. Zero means "no precondition", which is
	// only legal on operations whose contract says so.
	ExpectedVersion int64 `protobuf:"varint,1,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Precondition) Reset() {
	*x = Precondition{}
	mi := &file_payments_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Precondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Precondition) ProtoMessage() {}

func (x *Precondition) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Precondition.ProtoReflect.Descriptor instead.
func (*Precondition) Descriptor() ([]byte, []int) {
	return file_payments_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *Precondition) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

var File_payments_v1_common_proto protoreflect.FileDescriptor

var file_payments_v1_common_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x65,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x4a, 0x04, 0x08, 0x03, 0x10, 0x04, 0x52, 0x08, 0x65, 0x78, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x22, 0xad, 0x02, 0x0a, 0x0d, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x72, 0x63, 0x68,
	0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70,
	0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x69,
	0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65,
	0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x4a,
	0x04, 0x08, 0x09, 0x10, 0x10, 0x22, 0x4f, 0x0a, 0x0b, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x4a, 0x04, 0x08, 0x03, 0x10, 0x08, 0x22, 0x69, 0x0a, 0x0c, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2b,
	0x0a, 0x11, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x61, 0x70, 0x70, 0x72, 0x6f,
	0x78, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4a, 0x04, 0x08, 0x03, 0x10,
	0x08, 0x22, 0xca, 0x02, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x36, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x74, 0x72, 0x79, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x74, 0x72, 0x79, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x07, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x19, 0x0a,
	0x08, 0x64, 0x6f, 0x63, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x64, 0x6f, 0x63, 0x73, 0x55, 0x72, 0x6c, 0x12, 0x2e, 0x0a, 0x13, 0x72, 0x65, 0x74, 0x72,
	0x79, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x72, 0x65, 0x74, 0x72, 0x79, 0x41, 0x66, 0x74, 0x65,
	0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x4a, 0x04, 0x08, 0x0a, 0x10, 0x14, 0x22, 0x6a,
	0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x12, 0x49, 0x64,
	0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x06, 0x22, 0x79, 0x0a, 0x11, 0x49, 0x64, 0x65, 0x6d,
	0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x12, 0x48, 0x0a, 0x12, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x10, 0x66, 0x69, 0x72, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0x39, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x65,
	0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2a, 0x87,
	0x01, 0x0a, 0x09, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16,
	0x41, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x43, 0x54, 0x4f,
	0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x12, 0x19, 0x0a,
	0x15, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x50, 0x49, 0x5f,
	0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x43, 0x54, 0x4f,
	0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x03, 0x12,
	0x17, 0x0a, 0x13, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x57, 0x4f,
	0x52, 0x4b, 0x46, 0x4c, 0x4f, 0x57, 0x10, 0x04, 0x2a, 0x5f, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x4e, 0x56, 0x49, 0x52,
	0x4f, 0x4e, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x4e, 0x56, 0x49, 0x52, 0x4f, 0x4e, 0x4d,
	0x45, 0x4e, 0x54, 0x5f, 0x53, 0x41, 0x4e, 0x44, 0x42, 0x4f, 0x58, 0x10, 0x01, 0x12, 0x1a, 0x0a,
	0x16, 0x45, 0x4e, 0x56, 0x49, 0x52, 0x4f, 0x4e, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52, 0x4f,
	0x44, 0x55, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x2a, 0x87, 0x03, 0x0a, 0x0d, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x1a, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x21, 0x0a, 0x1d, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x41, 0x55, 0x54,
	0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x20, 0x0a,
	0x1c, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f,
	0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x12,
	0x1c, 0x0a, 0x18, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52,
	0x59, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x04, 0x12, 0x1b, 0x0a,
	0x17, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f,
	0x43, 0x4f, 0x4e, 0x46, 0x4c, 0x49, 0x43, 0x54, 0x10, 0x05, 0x12, 0x20, 0x0a, 0x1c, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x42, 0x55, 0x53,
	0x49, 0x4e, 0x45, 0x53, 0x53, 0x5f, 0x52, 0x55, 0x4c, 0x45, 0x10, 0x06, 0x12, 0x1d, 0x0a, 0x19,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x52,
	0x41, 0x54, 0x45, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10, 0x07, 0x12, 0x1a, 0x0a, 0x16, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x47, 0x41,
	0x54, 0x45, 0x57, 0x41, 0x59, 0x10, 0x08, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55,
	0x54, 0x10, 0x09, 0x12, 0x21, 0x0a, 0x1d, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x41, 0x54,
	0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x49, 0x4e, 0x46, 0x52, 0x41, 0x53, 0x54, 0x52, 0x55, 0x43,
	0x54, 0x55, 0x52, 0x45, 0x10, 0x0a, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f,
	0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41,
	0x4c, 0x10, 0x0b, 0x42, 0x8e, 0x01, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x42,
	0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x64, 0x61, 0x79, 0x6b,
	0x69, 0x73, 0x68, 0x6f, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x73, 0x75, 0x2f, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x2f, 0x76, 0x31, 0x3b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x76, 0x31, 0xaa, 0x02,
	0x13, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_payments_v1_common_proto_rawDescOnce sync.Once
	file_payments_v1_common_proto_rawDescData []byte
)

func file_payments_v1_common_proto_rawDescGZIP() []byte {
	file_payments_v1_common_proto_rawDescOnce.Do(func() {
		file_payments_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payments_v1_common_proto_rawDesc), len(file_payments_v1_common_proto_rawDesc)))
	})
	return file_payments_v1_common_proto_rawDescData
}

var file_payments_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_payments_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_payments_v1_common_proto_goTypes = []any{
	(ActorType)(0),                // 0: payments.v1.ActorType
	(Environment)(0),              // 1: payments.v1.Environment
	(ErrorCategory)(0),            // 2: payments.v1.ErrorCategory
	(*Money)(nil),                 // 3: payments.v1.Money
	(*TenantContext)(nil),         // 4: payments.v1.TenantContext
	(*PageRequest)(nil),           // 5: payments.v1.PageRequest
	(*PageResponse)(nil),          // 6: payments.v1.PageResponse
	(*Error)(nil),                 // 7: payments.v1.Error
	(*ErrorDetail)(nil),           // 8: payments.v1.ErrorDetail
	(*IdempotencyOptions)(nil),    // 9: payments.v1.IdempotencyOptions
	(*IdempotencyResult)(nil),     // 10: payments.v1.IdempotencyResult
	(*Precondition)(nil),          // 11: payments.v1.Precondition
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_payments_v1_common_proto_depIdxs = []int32{
	0,  // 0: payments.v1.TenantContext.actor_type:type_name -> payments.v1.ActorType
	2,  // 1: payments.v1.Error.category:type_name -> payments.v1.ErrorCategory
	8,  // 2: payments.v1.Error.details:type_name -> payments.v1.ErrorDetail
	12, // 3: payments.v1.IdempotencyResult.first_completed_at:type_name -> google.protobuf.Timestamp
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_payments_v1_common_proto_init() }
func file_payments_v1_common_proto_init() {
	if File_payments_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payments_v1_common_proto_rawDesc), len(file_payments_v1_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payments_v1_common_proto_goTypes,
		DependencyIndexes: file_payments_v1_common_proto_depIdxs,
		EnumInfos:         file_payments_v1_common_proto_enumTypes,
		MessageInfos:      file_payments_v1_common_proto_msgTypes,
	}.Build()
	File_payments_v1_common_proto = out.File
	file_payments_v1_common_proto_goTypes = nil
	file_payments_v1_common_proto_depIdxs = nil
}
