// Configuration and Policy (BC-5) internal interface.
//
// The control plane is the PUBLISHED-LANGUAGE SUPPLIER here and the data plane is its
// customer. The supplier may not break the customer's contract without a new major
// event version.
//
// The data plane never takes a synchronous dependency on this service for a payment. It
// warms a local snapshot from `configuration.published.v1`, tolerates 30 s of
// staleness, and FAILS STATIC: if the control plane is entirely down it keeps
// processing with its last-known-good snapshot rather than either stopping (which kills
// revenue) or ignoring limits (which kills compliance). Past max_config_staleness
// (15 min) it fails closed for NEW merchants while continuing to serve existing ones.
// Graceful degradation with a defined cliff.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: payments/v1/config.proto

package paymentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigurationService_GetActiveConfiguration_FullMethodName    = "/payments.v1.ConfigurationService/GetActiveConfiguration"
	ConfigurationService_ListActiveConfigurations_FullMethodName  = "/payments.v1.ConfigurationService/ListActiveConfigurations"
	ConfigurationService_ListConfigurationVersions_FullMethodName = "/payments.v1.ConfigurationService/ListConfigurationVersions"
	ConfigurationService_PublishConfiguration_FullMethodName      = "/payments.v1.ConfigurationService/PublishConfiguration"
	ConfigurationService_RollbackConfiguration_FullMethodName     = "/payments.v1.ConfigurationService/RollbackConfiguration"
	ConfigurationService_ValidateConfiguration_FullMethodName     = "/payments.v1.ConfigurationService/ValidateConfiguration"
	ConfigurationService_WatchConfigurations_FullMethodName       = "/payments.v1.ConfigurationService/WatchConfigurations"
)

// ConfigurationServiceClient is the client API for ConfigurationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Configuration and policy (BC-5).
type ConfigurationServiceClient interface {
	// Read the active configuration for one merchant.
	GetActiveConfiguration(ctx context.Context, in *GetActiveConfigurationRequest, opts ...grpc.CallOption) (*GetActiveConfigurationResponse, error)
	// Bulk read for warming a cold data-plane cache.
	ListActiveConfigurations(ctx context.Context, in *ListActiveConfigurationsRequest, opts ...grpc.CallOption) (*ListActiveConfigurationsResponse, error)
	// Cursor-paginated version history.
	ListConfigurationVersions(ctx context.Context, in *ListConfigurationVersionsRequest, opts ...grpc.CallOption) (*ListConfigurationVersionsResponse, error)
	// Publish a new version. Validated, versioned, audited and published as an event.
	PublishConfiguration(ctx context.Context, in *PublishConfigurationRequest, opts ...grpc.CallOption) (*PublishConfigurationResponse, error)
	// Roll back by re-publishing an earlier document as a new version, after re-validating
	// it against today's world.
	RollbackConfiguration(ctx context.Context, in *RollbackConfigurationRequest, opts ...grpc.CallOption) (*RollbackConfigurationResponse, error)
	// Validate without publishing. Pre-flight feedback for the console and for CI.
	ValidateConfiguration(ctx context.Context, in *ValidateConfigurationRequest, opts ...grpc.CallOption) (*ValidateConfigurationResponse, error)
	// Stream publications to a data-plane cache. An accelerator over the durable Kafka
	// path, never a replacement for it.
	WatchConfigurations(ctx context.Context, in *WatchConfigurationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchConfigurationsResponse], error)
}

type configurationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigurationServiceClient(cc grpc.ClientConnInterface) ConfigurationServiceClient {
	return &configurationServiceClient{cc}
}

func (c *configurationServiceClient) GetActiveConfiguration(ctx context.Context, in *GetActiveConfigurationRequest, opts ...grpc.CallOption) (*GetActiveConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveConfigurationResponse)
	err := c.cc.Invoke(ctx, ConfigurationService_GetActiveConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationServiceClient) ListActiveConfigurations(ctx context.Context, in *ListActiveConfigurationsRequest, opts ...grpc.CallOption) (*ListActiveConfigurationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveConfigurationsResponse)
	err := c.cc.Invoke(ctx, ConfigurationService_ListActiveConfigurations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationServiceClient) ListConfigurationVersions(ctx context.Context, in *ListConfigurationVersionsRequest, opts ...grpc.CallOption) (*ListConfigurationVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigurationVersionsResponse)
	err := c.cc.Invoke(ctx, ConfigurationService_ListConfigurationVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationServiceClient) PublishConfiguration(ctx context.Context, in *PublishConfigurationRequest, opts ...grpc.CallOption) (*PublishConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishConfigurationResponse)
	err := c.cc.Invoke(ctx, ConfigurationService_PublishConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationServiceClient) RollbackConfiguration(ctx context.Context, in *RollbackConfigurationRequest, opts ...grpc.CallOption) (*RollbackConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackConfigurationResponse)
	err := c.cc.Invoke(ctx, ConfigurationService_RollbackConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationServiceClient) ValidateConfiguration(ctx context.Context, in *ValidateConfigurationRequest, opts ...grpc.CallOption) (*ValidateConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateConfigurationResponse)
	err := c.cc.Invoke(ctx, ConfigurationService_ValidateConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationServiceClient) WatchConfigurations(ctx context.Context, in *WatchConfigurationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchConfigurationsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigurationService_ServiceDesc.Streams[0], ConfigurationService_WatchConfigurations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchConfigurationsRequest, WatchConfigurationsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigurationService_WatchConfigurationsClient = grpc.ServerStreamingClient[WatchConfigurationsResponse]

// ConfigurationServiceServer is the server API for ConfigurationService service.
// All implementations must embed UnimplementedConfigurationServiceServer
// for forward compatibility.
//
// Configuration and policy (BC-5).
type ConfigurationServiceServer interface {
	// Read the active configuration for one merchant.
	GetActiveConfiguration(context.Context, *GetActiveConfigurationRequest) (*GetActiveConfigurationResponse, error)
	// Bulk read for warming a cold data-plane cache.
	ListActiveConfigurations(context.Context, *ListActiveConfigurationsRequest) (*ListActiveConfigurationsResponse, error)
	// Cursor-paginated version history.
	ListConfigurationVersions(context.Context, *ListConfigurationVersionsRequest) (*ListConfigurationVersionsResponse, error)
	// Publish a new version. Validated, versioned, audited and published as an event.
	PublishConfiguration(context.Context, *PublishConfigurationRequest) (*PublishConfigurationResponse, error)
	// Roll back by re-publishing an earlier document as a new version, after re-validating
	// it against today's world.
	RollbackConfiguration(context.Context, *RollbackConfigurationRequest) (*RollbackConfigurationResponse, error)
	// Validate without publishing. Pre-flight feedback for the console and for CI.
	ValidateConfiguration(context.Context, *ValidateConfigurationRequest) (*ValidateConfigurationResponse, error)
	// Stream publications to a data-plane cache. An accelerator over the durable Kafka
	// path, never a replacement for it.
	WatchConfigurations(*WatchConfigurationsRequest, grpc.ServerStreamingServer[WatchConfigurationsResponse]) error
	mustEmbedUnimplementedConfigurationServiceServer()
}

// UnimplementedConfigurationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigurationServiceServer struct{}

func (UnimplementedConfigurationServiceServer) GetActiveConfiguration(context.Context, *GetActiveConfigurationRequest) (*GetActiveConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveConfiguration not implemented")
}
func (UnimplementedConfigurationServiceServer) ListActiveConfigurations(context.Context, *ListActiveConfigurationsRequest) (*ListActiveConfigurationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActiveConfigurations not implemented")
}
func (UnimplementedConfigurationServiceServer) ListConfigurationVersions(context.Context, *ListConfigurationVersionsRequest) (*ListConfigurationVersionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfigurationVersions not implemented")
}
func (UnimplementedConfigurationServiceServer) PublishConfiguration(context.Context, *PublishConfigurationRequest) (*PublishConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishConfiguration not implemented")
}
func (UnimplementedConfigurationServiceServer) RollbackConfiguration(context.Context, *RollbackConfigurationRequest) (*RollbackConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackConfiguration not implemented")
}
func (UnimplementedConfigurationServiceServer) ValidateConfiguration(context.Context, *ValidateConfigurationRequest) (*ValidateConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateConfiguration not implemented")
}
func (UnimplementedConfigurationServiceServer) WatchConfigurations(*WatchConfigurationsRequest, grpc.ServerStreamingServer[WatchConfigurationsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WatchConfigurations not implemented")
}
func (UnimplementedConfigurationServiceServer) mustEmbedUnimplementedConfigurationServiceServer() {}
func (UnimplementedConfigurationServiceServer) testEmbeddedByValue()                              {}

// UnsafeConfigurationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigurationServiceServer will
// result in compilation errors.
type UnsafeConfigurationServiceServer interface {
	mustEmbedUnimplementedConfigurationServiceServer()
}

func RegisterConfigurationServiceServer(s grpc.ServiceRegistrar, srv ConfigurationServiceServer) {
	// If the following call pancis, it indicates UnimplementedConfigurationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigurationService_ServiceDesc, srv)
}

func _ConfigurationService_GetActiveConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServiceServer).GetActiveConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationService_GetActiveConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServiceServer).GetActiveConfiguration(ctx, req.(*GetActiveConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationService_ListActiveConfigurations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveConfigurationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServiceServer).ListActiveConfigurations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationService_ListActiveConfigurations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServiceServer).ListActiveConfigurations(ctx, req.(*ListActiveConfigurationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationService_ListConfigurationVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigurationVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServiceServer).ListConfigurationVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationService_ListConfigurationVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServiceServer).ListConfigurationVersions(ctx, req.(*ListConfigurationVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationService_PublishConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServiceServer).PublishConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationService_PublishConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServiceServer).PublishConfiguration(ctx, req.(*PublishConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationService_RollbackConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServiceServer).RollbackConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationService_RollbackConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServiceServer).RollbackConfiguration(ctx, req.(*RollbackConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationService_ValidateConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServiceServer).ValidateConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationService_ValidateConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServiceServer).ValidateConfiguration(ctx, req.(*ValidateConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationService_WatchConfigurations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchConfigurationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigurationServiceServer).WatchConfigurations(m, &grpc.GenericServerStream[WatchConfigurationsRequest, WatchConfigurationsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigurationService_WatchConfigurationsServer = grpc.ServerStreamingServer[WatchConfigurationsResponse]

// ConfigurationService_ServiceDesc is the grpc.ServiceDesc for ConfigurationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigurationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payments.v1.ConfigurationService",
	HandlerType: (*ConfigurationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActiveConfiguration",
			Handler:    _ConfigurationService_GetActiveConfiguration_Handler,
		},
		{
			MethodName: "ListActiveConfigurations",
			Handler:    _ConfigurationService_ListActiveConfigurations_Handler,
		},
		{
			MethodName: "ListConfigurationVersions",
			Handler:    _ConfigurationService_ListConfigurationVersions_Handler,
		},
		{
			MethodName: "PublishConfiguration",
			Handler:    _ConfigurationService_PublishConfiguration_Handler,
		},
		{
			MethodName: "RollbackConfiguration",
			Handler:    _ConfigurationService_RollbackConfiguration_Handler,
		},
		{
			MethodName: "ValidateConfiguration",
			Handler:    _ConfigurationService_ValidateConfiguration_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchConfigurations",
			Handler:       _ConfigurationService_WatchConfigurations_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "payments/v1/config.proto",
}
