// Gateway Registry and Integration (BC-4) internal interface.
//
// Two halves with different availability classes, deliberately in one file because they
// share a vocabulary:
//   * The registry (control plane): gateways, capability descriptors, connections.
//   * Health and provisioning (data plane and automation plane): the feedback loop from
//     Observability back into Control, and the workflow activity callbacks for steps
//     5-7 and for credential rotation.
//
// No gateway type ever appears in the domain. Everything here is already translated by
// the anti-corruption layer.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: payments/v1/gateway.proto

package paymentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_GetGateway_FullMethodName             = "/payments.v1.GatewayService/GetGateway"
	GatewayService_ListGateways_FullMethodName           = "/payments.v1.GatewayService/ListGateways"
	GatewayService_GetGatewayHealth_FullMethodName       = "/payments.v1.GatewayService/GetGatewayHealth"
	GatewayService_WatchGatewayHealth_FullMethodName     = "/payments.v1.GatewayService/WatchGatewayHealth"
	GatewayService_ReportHealthTransition_FullMethodName = "/payments.v1.GatewayService/ReportHealthTransition"
	GatewayService_GetGatewayConnection_FullMethodName   = "/payments.v1.GatewayService/GetGatewayConnection"
	GatewayService_ListGatewayConnections_FullMethodName = "/payments.v1.GatewayService/ListGatewayConnections"
	GatewayService_ProvisionConnection_FullMethodName    = "/payments.v1.GatewayService/ProvisionConnection"
	GatewayService_RegisterWebhook_FullMethodName        = "/payments.v1.GatewayService/RegisterWebhook"
	GatewayService_RotateCredentials_FullMethodName      = "/payments.v1.GatewayService/RotateCredentials"
	GatewayService_UpdateConnectionState_FullMethodName  = "/payments.v1.GatewayService/UpdateConnectionState"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Gateway registry, health and provisioning (BC-4).
type GatewayServiceClient interface {
	// Read one gateway by identifier or by code.
	GetGateway(ctx context.Context, in *GetGatewayRequest, opts ...grpc.CallOption) (*GetGatewayResponse, error)
	// Cursor-paginated catalogue listing with capability filters.
	ListGateways(ctx context.Context, in *ListGatewaysRequest, opts ...grpc.CallOption) (*ListGatewaysResponse, error)
	// Read health for one gateway, per operation, in one region.
	GetGatewayHealth(ctx context.Context, in *GetGatewayHealthRequest, opts ...grpc.CallOption) (*GetGatewayHealthResponse, error)
	// Stream health transitions to the routing engine. An accelerator over the durable
	// Kafka path, never a replacement for it.
	WatchGatewayHealth(ctx context.Context, in *WatchGatewayHealthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchGatewayHealthResponse], error)
	// Report a health state change from an orchestrator pod. Called on transition only.
	ReportHealthTransition(ctx context.Context, in *ReportHealthTransitionRequest, opts ...grpc.CallOption) (*ReportHealthTransitionResponse, error)
	// Read one merchant-gateway connection.
	GetGatewayConnection(ctx context.Context, in *GetGatewayConnectionRequest, opts ...grpc.CallOption) (*GetGatewayConnectionResponse, error)
	// List a merchant's connections.
	ListGatewayConnections(ctx context.Context, in *ListGatewayConnectionsRequest, opts ...grpc.CallOption) (*ListGatewayConnectionsResponse, error)
	// Workflow activity callback: provision a merchant sub-account at a gateway.
	ProvisionConnection(ctx context.Context, in *ProvisionConnectionRequest, opts ...grpc.CallOption) (*ProvisionConnectionResponse, error)
	// Workflow activity callback: register our webhook endpoint at the gateway.
	RegisterWebhook(ctx context.Context, in *RegisterWebhookRequest, opts ...grpc.CallOption) (*RegisterWebhookResponse, error)
	// Rotate gateway credentials with a dual-run overlap.
	RotateCredentials(ctx context.Context, in *RotateCredentialsRequest, opts ...grpc.CallOption) (*RotateCredentialsResponse, error)
	// Transition a connection's state, e.g. to DEGRADED or REVOKED.
	UpdateConnectionState(ctx context.Context, in *UpdateConnectionStateRequest, opts ...grpc.CallOption) (*UpdateConnectionStateResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) GetGateway(ctx context.Context, in *GetGatewayRequest, opts ...grpc.CallOption) (*GetGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatewayResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListGateways(ctx context.Context, in *ListGatewaysRequest, opts ...grpc.CallOption) (*ListGatewaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGatewaysResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListGateways_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetGatewayHealth(ctx context.Context, in *GetGatewayHealthRequest, opts ...grpc.CallOption) (*GetGatewayHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatewayHealthResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetGatewayHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) WatchGatewayHealth(ctx context.Context, in *WatchGatewayHealthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchGatewayHealthResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[0], GatewayService_WatchGatewayHealth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchGatewayHealthRequest, WatchGatewayHealthResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_WatchGatewayHealthClient = grpc.ServerStreamingClient[WatchGatewayHealthResponse]

func (c *gatewayServiceClient) ReportHealthTransition(ctx context.Context, in *ReportHealthTransitionRequest, opts ...grpc.CallOption) (*ReportHealthTransitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportHealthTransitionResponse)
	err := c.cc.Invoke(ctx, GatewayService_ReportHealthTransition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetGatewayConnection(ctx context.Context, in *GetGatewayConnectionRequest, opts ...grpc.CallOption) (*GetGatewayConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatewayConnectionResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetGatewayConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListGatewayConnections(ctx context.Context, in *ListGatewayConnectionsRequest, opts ...grpc.CallOption) (*ListGatewayConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGatewayConnectionsResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListGatewayConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ProvisionConnection(ctx context.Context, in *ProvisionConnectionRequest, opts ...grpc.CallOption) (*ProvisionConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionConnectionResponse)
	err := c.cc.Invoke(ctx, GatewayService_ProvisionConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) RegisterWebhook(ctx context.Context, in *RegisterWebhookRequest, opts ...grpc.CallOption) (*RegisterWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWebhookResponse)
	err := c.cc.Invoke(ctx, GatewayService_RegisterWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) RotateCredentials(ctx context.Context, in *RotateCredentialsRequest, opts ...grpc.CallOption) (*RotateCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateCredentialsResponse)
	err := c.cc.Invoke(ctx, GatewayService_RotateCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) UpdateConnectionState(ctx context.Context, in *UpdateConnectionStateRequest, opts ...grpc.CallOption) (*UpdateConnectionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConnectionStateResponse)
	err := c.cc.Invoke(ctx, GatewayService_UpdateConnectionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
//
// Gateway registry, health and provisioning (BC-4).
type GatewayServiceServer interface {
	// Read one gateway by identifier or by code.
	GetGateway(context.Context, *GetGatewayRequest) (*GetGatewayResponse, error)
	// Cursor-paginated catalogue listing with capability filters.
	ListGateways(context.Context, *ListGatewaysRequest) (*ListGatewaysResponse, error)
	// Read health for one gateway, per operation, in one region.
	GetGatewayHealth(context.Context, *GetGatewayHealthRequest) (*GetGatewayHealthResponse, error)
	// Stream health transitions to the routing engine. An accelerator over the durable
	// Kafka path, never a replacement for it.
	WatchGatewayHealth(*WatchGatewayHealthRequest, grpc.ServerStreamingServer[WatchGatewayHealthResponse]) error
	// Report a health state change from an orchestrator pod. Called on transition only.
	ReportHealthTransition(context.Context, *ReportHealthTransitionRequest) (*ReportHealthTransitionResponse, error)
	// Read one merchant-gateway connection.
	GetGatewayConnection(context.Context, *GetGatewayConnectionRequest) (*GetGatewayConnectionResponse, error)
	// List a merchant's connections.
	ListGatewayConnections(context.Context, *ListGatewayConnectionsRequest) (*ListGatewayConnectionsResponse, error)
	// Workflow activity callback: provision a merchant sub-account at a gateway.
	ProvisionConnection(context.Context, *ProvisionConnectionRequest) (*ProvisionConnectionResponse, error)
	// Workflow activity callback: register our webhook endpoint at the gateway.
	RegisterWebhook(context.Context, *RegisterWebhookRequest) (*RegisterWebhookResponse, error)
	// Rotate gateway credentials with a dual-run overlap.
	RotateCredentials(context.Context, *RotateCredentialsRequest) (*RotateCredentialsResponse, error)
	// Transition a connection's state, e.g. to DEGRADED or REVOKED.
	UpdateConnectionState(context.Context, *UpdateConnectionStateRequest) (*UpdateConnectionStateResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) GetGateway(context.Context, *GetGatewayRequest) (*GetGatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGateway not implemented")
}
func (UnimplementedGatewayServiceServer) ListGateways(context.Context, *ListGatewaysRequest) (*ListGatewaysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGateways not implemented")
}
func (UnimplementedGatewayServiceServer) GetGatewayHealth(context.Context, *GetGatewayHealthRequest) (*GetGatewayHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayHealth not implemented")
}
func (UnimplementedGatewayServiceServer) WatchGatewayHealth(*WatchGatewayHealthRequest, grpc.ServerStreamingServer[WatchGatewayHealthResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WatchGatewayHealth not implemented")
}
func (UnimplementedGatewayServiceServer) ReportHealthTransition(context.Context, *ReportHealthTransitionRequest) (*ReportHealthTransitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportHealthTransition not implemented")
}
func (UnimplementedGatewayServiceServer) GetGatewayConnection(context.Context, *GetGatewayConnectionRequest) (*GetGatewayConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayConnection not implemented")
}
func (UnimplementedGatewayServiceServer) ListGatewayConnections(context.Context, *ListGatewayConnectionsRequest) (*ListGatewayConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGatewayConnections not implemented")
}
func (UnimplementedGatewayServiceServer) ProvisionConnection(context.Context, *ProvisionConnectionRequest) (*ProvisionConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionConnection not implemented")
}
func (UnimplementedGatewayServiceServer) RegisterWebhook(context.Context, *RegisterWebhookRequest) (*RegisterWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWebhook not implemented")
}
func (UnimplementedGatewayServiceServer) RotateCredentials(context.Context, *RotateCredentialsRequest) (*RotateCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateCredentials not implemented")
}
func (UnimplementedGatewayServiceServer) UpdateConnectionState(context.Context, *UpdateConnectionStateRequest) (*UpdateConnectionStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConnectionState not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_GetGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetGateway(ctx, req.(*GetGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListGateways_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGatewaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListGateways(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListGateways_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListGateways(ctx, req.(*ListGatewaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetGatewayHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetGatewayHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetGatewayHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetGatewayHealth(ctx, req.(*GetGatewayHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_WatchGatewayHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchGatewayHealthRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServiceServer).WatchGatewayHealth(m, &grpc.GenericServerStream[WatchGatewayHealthRequest, WatchGatewayHealthResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_WatchGatewayHealthServer = grpc.ServerStreamingServer[WatchGatewayHealthResponse]

func _GatewayService_ReportHealthTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportHealthTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ReportHealthTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ReportHealthTransition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ReportHealthTransition(ctx, req.(*ReportHealthTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetGatewayConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetGatewayConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetGatewayConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetGatewayConnection(ctx, req.(*GetGatewayConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListGatewayConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGatewayConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListGatewayConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListGatewayConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListGatewayConnections(ctx, req.(*ListGatewayConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ProvisionConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ProvisionConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ProvisionConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ProvisionConnection(ctx, req.(*ProvisionConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_RegisterWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).RegisterWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_RegisterWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).RegisterWebhook(ctx, req.(*RegisterWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_RotateCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).RotateCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_RotateCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).RotateCredentials(ctx, req.(*RotateCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_UpdateConnectionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConnectionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).UpdateConnectionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_UpdateConnectionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).UpdateConnectionState(ctx, req.(*UpdateConnectionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payments.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGateway",
			Handler:    _GatewayService_GetGateway_Handler,
		},
		{
			MethodName: "ListGateways",
			Handler:    _GatewayService_ListGateways_Handler,
		},
		{
			MethodName: "GetGatewayHealth",
			Handler:    _GatewayService_GetGatewayHealth_Handler,
		},
		{
			MethodName: "ReportHealthTransition",
			Handler:    _GatewayService_ReportHealthTransition_Handler,
		},
		{
			MethodName: "GetGatewayConnection",
			Handler:    _GatewayService_GetGatewayConnection_Handler,
		},
		{
			MethodName: "ListGatewayConnections",
			Handler:    _GatewayService_ListGatewayConnections_Handler,
		},
		{
			MethodName: "ProvisionConnection",
			Handler:    _GatewayService_ProvisionConnection_Handler,
		},
		{
			MethodName: "RegisterWebhook",
			Handler:    _GatewayService_RegisterWebhook_Handler,
		},
		{
			MethodName: "RotateCredentials",
			Handler:    _GatewayService_RotateCredentials_Handler,
		},
		{
			MethodName: "UpdateConnectionState",
			Handler:    _GatewayService_UpdateConnectionState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchGatewayHealth",
			Handler:       _GatewayService_WatchGatewayHealth_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "payments/v1/gateway.proto",
}
