// Merchant Registry (BC-2) internal interface.
//
// This is the control-plane read the data plane depends on, plus the small set of
// writes the automation plane is allowed to request. It is NOT the public merchant API
// - that is REST, in api/openapi/payments-platform.v1.yaml.
//
// The data plane calls GetMerchantContext on its cache-miss path only. It must never
// take a synchronous dependency on this service for a payment: the cache is warmed by
// events, tolerates 30 s of staleness, and fails static rather than open.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: payments/v1/merchant.proto

package paymentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MerchantService_GetMerchant_FullMethodName               = "/payments.v1.MerchantService/GetMerchant"
	MerchantService_BatchGetMerchants_FullMethodName         = "/payments.v1.MerchantService/BatchGetMerchants"
	MerchantService_ListMerchants_FullMethodName             = "/payments.v1.MerchantService/ListMerchants"
	MerchantService_GetMerchantContext_FullMethodName        = "/payments.v1.MerchantService/GetMerchantContext"
	MerchantService_ListMerchantContexts_FullMethodName      = "/payments.v1.MerchantService/ListMerchantContexts"
	MerchantService_TransitionMerchantStatus_FullMethodName  = "/payments.v1.MerchantService/TransitionMerchantStatus"
	MerchantService_SuspendMerchant_FullMethodName           = "/payments.v1.MerchantService/SuspendMerchant"
	MerchantService_ResumeMerchant_FullMethodName            = "/payments.v1.MerchantService/ResumeMerchant"
	MerchantService_AttachCertificationReport_FullMethodName = "/payments.v1.MerchantService/AttachCertificationReport"
)

// MerchantServiceClient is the client API for MerchantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Merchant Registry (BC-2).
//
// Reads are safe and cacheable. Writes are the narrow set the automation plane needs;
// everything a human does goes through the REST control plane so it passes the same
// authorization, dual-control and audit path.
type MerchantServiceClient interface {
	// Fetch one merchant with its business profile, bank accounts and principals.
	GetMerchant(ctx context.Context, in *GetMerchantRequest, opts ...grpc.CallOption) (*GetMerchantResponse, error)
	// Fetch several merchants in one round trip. Not for the payment hot path.
	BatchGetMerchants(ctx context.Context, in *BatchGetMerchantsRequest, opts ...grpc.CallOption) (*BatchGetMerchantsResponse, error)
	// Cursor-paginated listing within the caller's tenant.
	ListMerchants(ctx context.Context, in *ListMerchantsRequest, opts ...grpc.CallOption) (*ListMerchantsResponse, error)
	// The narrow projection the data plane needs to admit a payment. Called only on a
	// cache miss; the steady-state path is served from the event-warmed local cache.
	GetMerchantContext(ctx context.Context, in *GetMerchantContextRequest, opts ...grpc.CallOption) (*GetMerchantContextResponse, error)
	// Bulk projections for warming a cold data-plane cache after a deploy or a restart.
	ListMerchantContexts(ctx context.Context, in *ListMerchantContextsRequest, opts ...grpc.CallOption) (*ListMerchantContextsResponse, error)
	// Request a lifecycle transition. Guards are enforced by the aggregate; an illegal
	// transition is FAILED_PRECONDITION / INVALID_STATE_TRANSITION.
	TransitionMerchantStatus(ctx context.Context, in *TransitionMerchantStatusRequest, opts ...grpc.CallOption) (*TransitionMerchantStatusResponse, error)
	// Suspend a merchant. Rejects new payments; refunds and voids continue.
	SuspendMerchant(ctx context.Context, in *SuspendMerchantRequest, opts ...grpc.CallOption) (*SuspendMerchantResponse, error)
	// Resume a suspended merchant.
	ResumeMerchant(ctx context.Context, in *ResumeMerchantRequest, opts ...grpc.CallOption) (*ResumeMerchantResponse, error)
	// Attach a passing certification report. Workflow activity callback for step 10.
	AttachCertificationReport(ctx context.Context, in *AttachCertificationReportRequest, opts ...grpc.CallOption) (*AttachCertificationReportResponse, error)
}

type merchantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantServiceClient(cc grpc.ClientConnInterface) MerchantServiceClient {
	return &merchantServiceClient{cc}
}

func (c *merchantServiceClient) GetMerchant(ctx context.Context, in *GetMerchantRequest, opts ...grpc.CallOption) (*GetMerchantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMerchantResponse)
	err := c.cc.Invoke(ctx, MerchantService_GetMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) BatchGetMerchants(ctx context.Context, in *BatchGetMerchantsRequest, opts ...grpc.CallOption) (*BatchGetMerchantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetMerchantsResponse)
	err := c.cc.Invoke(ctx, MerchantService_BatchGetMerchants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) ListMerchants(ctx context.Context, in *ListMerchantsRequest, opts ...grpc.CallOption) (*ListMerchantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMerchantsResponse)
	err := c.cc.Invoke(ctx, MerchantService_ListMerchants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) GetMerchantContext(ctx context.Context, in *GetMerchantContextRequest, opts ...grpc.CallOption) (*GetMerchantContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMerchantContextResponse)
	err := c.cc.Invoke(ctx, MerchantService_GetMerchantContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) ListMerchantContexts(ctx context.Context, in *ListMerchantContextsRequest, opts ...grpc.CallOption) (*ListMerchantContextsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMerchantContextsResponse)
	err := c.cc.Invoke(ctx, MerchantService_ListMerchantContexts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) TransitionMerchantStatus(ctx context.Context, in *TransitionMerchantStatusRequest, opts ...grpc.CallOption) (*TransitionMerchantStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionMerchantStatusResponse)
	err := c.cc.Invoke(ctx, MerchantService_TransitionMerchantStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) SuspendMerchant(ctx context.Context, in *SuspendMerchantRequest, opts ...grpc.CallOption) (*SuspendMerchantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendMerchantResponse)
	err := c.cc.Invoke(ctx, MerchantService_SuspendMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) ResumeMerchant(ctx context.Context, in *ResumeMerchantRequest, opts ...grpc.CallOption) (*ResumeMerchantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeMerchantResponse)
	err := c.cc.Invoke(ctx, MerchantService_ResumeMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) AttachCertificationReport(ctx context.Context, in *AttachCertificationReportRequest, opts ...grpc.CallOption) (*AttachCertificationReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachCertificationReportResponse)
	err := c.cc.Invoke(ctx, MerchantService_AttachCertificationReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantServiceServer is the server API for MerchantService service.
// All implementations must embed UnimplementedMerchantServiceServer
// for forward compatibility.
//
// Merchant Registry (BC-2).
//
// Reads are safe and cacheable. Writes are the narrow set the automation plane needs;
// everything a human does goes through the REST control plane so it passes the same
// authorization, dual-control and audit path.
type MerchantServiceServer interface {
	// Fetch one merchant with its business profile, bank accounts and principals.
	GetMerchant(context.Context, *GetMerchantRequest) (*GetMerchantResponse, error)
	// Fetch several merchants in one round trip. Not for the payment hot path.
	BatchGetMerchants(context.Context, *BatchGetMerchantsRequest) (*BatchGetMerchantsResponse, error)
	// Cursor-paginated listing within the caller's tenant.
	ListMerchants(context.Context, *ListMerchantsRequest) (*ListMerchantsResponse, error)
	// The narrow projection the data plane needs to admit a payment. Called only on a
	// cache miss; the steady-state path is served from the event-warmed local cache.
	GetMerchantContext(context.Context, *GetMerchantContextRequest) (*GetMerchantContextResponse, error)
	// Bulk projections for warming a cold data-plane cache after a deploy or a restart.
	ListMerchantContexts(context.Context, *ListMerchantContextsRequest) (*ListMerchantContextsResponse, error)
	// Request a lifecycle transition. Guards are enforced by the aggregate; an illegal
	// transition is FAILED_PRECONDITION / INVALID_STATE_TRANSITION.
	TransitionMerchantStatus(context.Context, *TransitionMerchantStatusRequest) (*TransitionMerchantStatusResponse, error)
	// Suspend a merchant. Rejects new payments; refunds and voids continue.
	SuspendMerchant(context.Context, *SuspendMerchantRequest) (*SuspendMerchantResponse, error)
	// Resume a suspended merchant.
	ResumeMerchant(context.Context, *ResumeMerchantRequest) (*ResumeMerchantResponse, error)
	// Attach a passing certification report. Workflow activity callback for step 10.
	AttachCertificationReport(context.Context, *AttachCertificationReportRequest) (*AttachCertificationReportResponse, error)
	mustEmbedUnimplementedMerchantServiceServer()
}

// UnimplementedMerchantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantServiceServer struct{}

func (UnimplementedMerchantServiceServer) GetMerchant(context.Context, *GetMerchantRequest) (*GetMerchantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerchant not implemented")
}
func (UnimplementedMerchantServiceServer) BatchGetMerchants(context.Context, *BatchGetMerchantsRequest) (*BatchGetMerchantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetMerchants not implemented")
}
func (UnimplementedMerchantServiceServer) ListMerchants(context.Context, *ListMerchantsRequest) (*ListMerchantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMerchants not implemented")
}
func (UnimplementedMerchantServiceServer) GetMerchantContext(context.Context, *GetMerchantContextRequest) (*GetMerchantContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerchantContext not implemented")
}
func (UnimplementedMerchantServiceServer) ListMerchantContexts(context.Context, *ListMerchantContextsRequest) (*ListMerchantContextsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMerchantContexts not implemented")
}
func (UnimplementedMerchantServiceServer) TransitionMerchantStatus(context.Context, *TransitionMerchantStatusRequest) (*TransitionMerchantStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionMerchantStatus not implemented")
}
func (UnimplementedMerchantServiceServer) SuspendMerchant(context.Context, *SuspendMerchantRequest) (*SuspendMerchantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendMerchant not implemented")
}
func (UnimplementedMerchantServiceServer) ResumeMerchant(context.Context, *ResumeMerchantRequest) (*ResumeMerchantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeMerchant not implemented")
}
func (UnimplementedMerchantServiceServer) AttachCertificationReport(context.Context, *AttachCertificationReportRequest) (*AttachCertificationReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachCertificationReport not implemented")
}
func (UnimplementedMerchantServiceServer) mustEmbedUnimplementedMerchantServiceServer() {}
func (UnimplementedMerchantServiceServer) testEmbeddedByValue()                         {}

// UnsafeMerchantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantServiceServer will
// result in compilation errors.
type UnsafeMerchantServiceServer interface {
	mustEmbedUnimplementedMerchantServiceServer()
}

func RegisterMerchantServiceServer(s grpc.ServiceRegistrar, srv MerchantServiceServer) {
	// If the following call pancis, it indicates UnimplementedMerchantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantService_ServiceDesc, srv)
}

func _MerchantService_GetMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).GetMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_GetMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).GetMerchant(ctx, req.(*GetMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_BatchGetMerchants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetMerchantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).BatchGetMerchants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_BatchGetMerchants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).BatchGetMerchants(ctx, req.(*BatchGetMerchantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_ListMerchants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMerchantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).ListMerchants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_ListMerchants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).ListMerchants(ctx, req.(*ListMerchantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_GetMerchantContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).GetMerchantContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_GetMerchantContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).GetMerchantContext(ctx, req.(*GetMerchantContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_ListMerchantContexts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMerchantContextsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).ListMerchantContexts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_ListMerchantContexts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).ListMerchantContexts(ctx, req.(*ListMerchantContextsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_TransitionMerchantStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionMerchantStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).TransitionMerchantStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_TransitionMerchantStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).TransitionMerchantStatus(ctx, req.(*TransitionMerchantStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_SuspendMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).SuspendMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_SuspendMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).SuspendMerchant(ctx, req.(*SuspendMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_ResumeMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).ResumeMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_ResumeMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).ResumeMerchant(ctx, req.(*ResumeMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_AttachCertificationReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachCertificationReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).AttachCertificationReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_AttachCertificationReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).AttachCertificationReport(ctx, req.(*AttachCertificationReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantService_ServiceDesc is the grpc.ServiceDesc for MerchantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payments.v1.MerchantService",
	HandlerType: (*MerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMerchant",
			Handler:    _MerchantService_GetMerchant_Handler,
		},
		{
			MethodName: "BatchGetMerchants",
			Handler:    _MerchantService_BatchGetMerchants_Handler,
		},
		{
			MethodName: "ListMerchants",
			Handler:    _MerchantService_ListMerchants_Handler,
		},
		{
			MethodName: "GetMerchantContext",
			Handler:    _MerchantService_GetMerchantContext_Handler,
		},
		{
			MethodName: "ListMerchantContexts",
			Handler:    _MerchantService_ListMerchantContexts_Handler,
		},
		{
			MethodName: "TransitionMerchantStatus",
			Handler:    _MerchantService_TransitionMerchantStatus_Handler,
		},
		{
			MethodName: "SuspendMerchant",
			Handler:    _MerchantService_SuspendMerchant_Handler,
		},
		{
			MethodName: "ResumeMerchant",
			Handler:    _MerchantService_ResumeMerchant_Handler,
		},
		{
			MethodName: "AttachCertificationReport",
			Handler:    _MerchantService_AttachCertificationReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payments/v1/merchant.proto",
}
