// Onboarding (BC-3) internal interface.
//
// Two audiences:
//   * The control plane and console, which read cases and deliver signals.
//   * The workflow worker, which reports activity results back to the engine. Those
//     RPCs are the activity callbacks; they are the reason this service exists as gRPC
//     rather than only as REST.
//
// Every step's result is checkpointed BEFORE the next step begins, resuming replays no
// completed step, an aborted instance runs compensations in strict reverse order, and a
// step that exhausts its retries moves the instance to FAILED with the full error chain
// in the workflow DLQ.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: payments/v1/onboarding.proto

package paymentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OnboardingService_StartOnboarding_FullMethodName           = "/payments.v1.OnboardingService/StartOnboarding"
	OnboardingService_GetOnboardingCase_FullMethodName         = "/payments.v1.OnboardingService/GetOnboardingCase"
	OnboardingService_ListOnboardingCases_FullMethodName       = "/payments.v1.OnboardingService/ListOnboardingCases"
	OnboardingService_SignalWorkflow_FullMethodName            = "/payments.v1.OnboardingService/SignalWorkflow"
	OnboardingService_ReportStepResult_FullMethodName          = "/payments.v1.OnboardingService/ReportStepResult"
	OnboardingService_RecordCertificationReport_FullMethodName = "/payments.v1.OnboardingService/RecordCertificationReport"
	OnboardingService_GetCertificationReport_FullMethodName    = "/payments.v1.OnboardingService/GetCertificationReport"
	OnboardingService_AbortOnboarding_FullMethodName           = "/payments.v1.OnboardingService/AbortOnboarding"
)

// OnboardingServiceClient is the client API for OnboardingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Onboarding orchestration (BC-3).
type OnboardingServiceClient interface {
	// Start the workflow. Idempotent on the merchant business key.
	StartOnboarding(ctx context.Context, in *StartOnboardingRequest, opts ...grpc.CallOption) (*StartOnboardingResponse, error)
	// Read a case with its step history and annotations.
	GetOnboardingCase(ctx context.Context, in *GetOnboardingCaseRequest, opts ...grpc.CallOption) (*GetOnboardingCaseResponse, error)
	// Cursor-paginated listing, used to build operator queues.
	ListOnboardingCases(ctx context.Context, in *ListOnboardingCasesRequest, opts ...grpc.CallOption) (*ListOnboardingCasesResponse, error)
	// Deliver a durable signal to a parked workflow instance.
	SignalWorkflow(ctx context.Context, in *SignalWorkflowRequest, opts ...grpc.CallOption) (*SignalWorkflowResponse, error)
	// Workflow activity callback. Reports a step result and checkpoints it.
	ReportStepResult(ctx context.Context, in *ReportStepResultRequest, opts ...grpc.CallOption) (*ReportStepResultResponse, error)
	// Workflow activity callback. Seals a certification report.
	RecordCertificationReport(ctx context.Context, in *RecordCertificationReportRequest, opts ...grpc.CallOption) (*RecordCertificationReportResponse, error)
	// Read a certification report by identifier.
	GetCertificationReport(ctx context.Context, in *GetCertificationReportRequest, opts ...grpc.CallOption) (*GetCertificationReportResponse, error)
	// Abort a running workflow and run compensations in reverse order.
	AbortOnboarding(ctx context.Context, in *AbortOnboardingRequest, opts ...grpc.CallOption) (*AbortOnboardingResponse, error)
}

type onboardingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnboardingServiceClient(cc grpc.ClientConnInterface) OnboardingServiceClient {
	return &onboardingServiceClient{cc}
}

func (c *onboardingServiceClient) StartOnboarding(ctx context.Context, in *StartOnboardingRequest, opts ...grpc.CallOption) (*StartOnboardingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartOnboardingResponse)
	err := c.cc.Invoke(ctx, OnboardingService_StartOnboarding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardingServiceClient) GetOnboardingCase(ctx context.Context, in *GetOnboardingCaseRequest, opts ...grpc.CallOption) (*GetOnboardingCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOnboardingCaseResponse)
	err := c.cc.Invoke(ctx, OnboardingService_GetOnboardingCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardingServiceClient) ListOnboardingCases(ctx context.Context, in *ListOnboardingCasesRequest, opts ...grpc.CallOption) (*ListOnboardingCasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOnboardingCasesResponse)
	err := c.cc.Invoke(ctx, OnboardingService_ListOnboardingCases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardingServiceClient) SignalWorkflow(ctx context.Context, in *SignalWorkflowRequest, opts ...grpc.CallOption) (*SignalWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalWorkflowResponse)
	err := c.cc.Invoke(ctx, OnboardingService_SignalWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardingServiceClient) ReportStepResult(ctx context.Context, in *ReportStepResultRequest, opts ...grpc.CallOption) (*ReportStepResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStepResultResponse)
	err := c.cc.Invoke(ctx, OnboardingService_ReportStepResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardingServiceClient) RecordCertificationReport(ctx context.Context, in *RecordCertificationReportRequest, opts ...grpc.CallOption) (*RecordCertificationReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordCertificationReportResponse)
	err := c.cc.Invoke(ctx, OnboardingService_RecordCertificationReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardingServiceClient) GetCertificationReport(ctx context.Context, in *GetCertificationReportRequest, opts ...grpc.CallOption) (*GetCertificationReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCertificationReportResponse)
	err := c.cc.Invoke(ctx, OnboardingService_GetCertificationReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardingServiceClient) AbortOnboarding(ctx context.Context, in *AbortOnboardingRequest, opts ...grpc.CallOption) (*AbortOnboardingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortOnboardingResponse)
	err := c.cc.Invoke(ctx, OnboardingService_AbortOnboarding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnboardingServiceServer is the server API for OnboardingService service.
// All implementations must embed UnimplementedOnboardingServiceServer
// for forward compatibility.
//
// Onboarding orchestration (BC-3).
type OnboardingServiceServer interface {
	// Start the workflow. Idempotent on the merchant business key.
	StartOnboarding(context.Context, *StartOnboardingRequest) (*StartOnboardingResponse, error)
	// Read a case with its step history and annotations.
	GetOnboardingCase(context.Context, *GetOnboardingCaseRequest) (*GetOnboardingCaseResponse, error)
	// Cursor-paginated listing, used to build operator queues.
	ListOnboardingCases(context.Context, *ListOnboardingCasesRequest) (*ListOnboardingCasesResponse, error)
	// Deliver a durable signal to a parked workflow instance.
	SignalWorkflow(context.Context, *SignalWorkflowRequest) (*SignalWorkflowResponse, error)
	// Workflow activity callback. Reports a step result and checkpoints it.
	ReportStepResult(context.Context, *ReportStepResultRequest) (*ReportStepResultResponse, error)
	// Workflow activity callback. Seals a certification report.
	RecordCertificationReport(context.Context, *RecordCertificationReportRequest) (*RecordCertificationReportResponse, error)
	// Read a certification report by identifier.
	GetCertificationReport(context.Context, *GetCertificationReportRequest) (*GetCertificationReportResponse, error)
	// Abort a running workflow and run compensations in reverse order.
	AbortOnboarding(context.Context, *AbortOnboardingRequest) (*AbortOnboardingResponse, error)
	mustEmbedUnimplementedOnboardingServiceServer()
}

// UnimplementedOnboardingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnboardingServiceServer struct{}

func (UnimplementedOnboardingServiceServer) StartOnboarding(context.Context, *StartOnboardingRequest) (*StartOnboardingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartOnboarding not implemented")
}
func (UnimplementedOnboardingServiceServer) GetOnboardingCase(context.Context, *GetOnboardingCaseRequest) (*GetOnboardingCaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnboardingCase not implemented")
}
func (UnimplementedOnboardingServiceServer) ListOnboardingCases(context.Context, *ListOnboardingCasesRequest) (*ListOnboardingCasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOnboardingCases not implemented")
}
func (UnimplementedOnboardingServiceServer) SignalWorkflow(context.Context, *SignalWorkflowRequest) (*SignalWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalWorkflow not implemented")
}
func (UnimplementedOnboardingServiceServer) ReportStepResult(context.Context, *ReportStepResultRequest) (*ReportStepResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportStepResult not implemented")
}
func (UnimplementedOnboardingServiceServer) RecordCertificationReport(context.Context, *RecordCertificationReportRequest) (*RecordCertificationReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordCertificationReport not implemented")
}
func (UnimplementedOnboardingServiceServer) GetCertificationReport(context.Context, *GetCertificationReportRequest) (*GetCertificationReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCertificationReport not implemented")
}
func (UnimplementedOnboardingServiceServer) AbortOnboarding(context.Context, *AbortOnboardingRequest) (*AbortOnboardingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortOnboarding not implemented")
}
func (UnimplementedOnboardingServiceServer) mustEmbedUnimplementedOnboardingServiceServer() {}
func (UnimplementedOnboardingServiceServer) testEmbeddedByValue()                           {}

// UnsafeOnboardingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnboardingServiceServer will
// result in compilation errors.
type UnsafeOnboardingServiceServer interface {
	mustEmbedUnimplementedOnboardingServiceServer()
}

func RegisterOnboardingServiceServer(s grpc.ServiceRegistrar, srv OnboardingServiceServer) {
	// If the following call pancis, it indicates UnimplementedOnboardingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OnboardingService_ServiceDesc, srv)
}

func _OnboardingService_StartOnboarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartOnboardingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardingServiceServer).StartOnboarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardingService_StartOnboarding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardingServiceServer).StartOnboarding(ctx, req.(*StartOnboardingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnboardingService_GetOnboardingCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnboardingCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardingServiceServer).GetOnboardingCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardingService_GetOnboardingCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardingServiceServer).GetOnboardingCase(ctx, req.(*GetOnboardingCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnboardingService_ListOnboardingCases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOnboardingCasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardingServiceServer).ListOnboardingCases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardingService_ListOnboardingCases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardingServiceServer).ListOnboardingCases(ctx, req.(*ListOnboardingCasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnboardingService_SignalWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardingServiceServer).SignalWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardingService_SignalWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardingServiceServer).SignalWorkflow(ctx, req.(*SignalWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnboardingService_ReportStepResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStepResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardingServiceServer).ReportStepResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardingService_ReportStepResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardingServiceServer).ReportStepResult(ctx, req.(*ReportStepResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnboardingService_RecordCertificationReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordCertificationReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardingServiceServer).RecordCertificationReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardingService_RecordCertificationReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardingServiceServer).RecordCertificationReport(ctx, req.(*RecordCertificationReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnboardingService_GetCertificationReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificationReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardingServiceServer).GetCertificationReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardingService_GetCertificationReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardingServiceServer).GetCertificationReport(ctx, req.(*GetCertificationReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnboardingService_AbortOnboarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortOnboardingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardingServiceServer).AbortOnboarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardingService_AbortOnboarding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardingServiceServer).AbortOnboarding(ctx, req.(*AbortOnboardingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OnboardingService_ServiceDesc is the grpc.ServiceDesc for OnboardingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnboardingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payments.v1.OnboardingService",
	HandlerType: (*OnboardingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartOnboarding",
			Handler:    _OnboardingService_StartOnboarding_Handler,
		},
		{
			MethodName: "GetOnboardingCase",
			Handler:    _OnboardingService_GetOnboardingCase_Handler,
		},
		{
			MethodName: "ListOnboardingCases",
			Handler:    _OnboardingService_ListOnboardingCases_Handler,
		},
		{
			MethodName: "SignalWorkflow",
			Handler:    _OnboardingService_SignalWorkflow_Handler,
		},
		{
			MethodName: "ReportStepResult",
			Handler:    _OnboardingService_ReportStepResult_Handler,
		},
		{
			MethodName: "RecordCertificationReport",
			Handler:    _OnboardingService_RecordCertificationReport_Handler,
		},
		{
			MethodName: "GetCertificationReport",
			Handler:    _OnboardingService_GetCertificationReport_Handler,
		},
		{
			MethodName: "AbortOnboarding",
			Handler:    _OnboardingService_AbortOnboarding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payments/v1/onboarding.proto",
}
