// Payment Orchestration (BC-6) internal interface.
//
// `payment-api` speaks this to `payment-orchestrator`. They are separate binaries so a
// slow gateway cannot consume the ingress connection pool, and so ingress scales on
// connection count while orchestration scales on in-flight gateway calls.
//
// THE TIMEOUT RULE governs this whole file. If a gateway call times out or returns an
// ambiguous transport error, the attempt is recorded TIMEOUT_UNKNOWN and the payment
// STAYS in PROCESSING. The caller receives a normal response carrying that state, not
// an error. No timer may fail a payment. Only a gateway webhook, a reconciler lookup
// keyed on our deterministic gateway idempotency key, or a settlement report can move
// it out.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: payments/v1/payment.proto

package paymentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_CreatePayment_FullMethodName              = "/payments.v1.PaymentService/CreatePayment"
	PaymentService_GetPayment_FullMethodName                 = "/payments.v1.PaymentService/GetPayment"
	PaymentService_ListPayments_FullMethodName               = "/payments.v1.PaymentService/ListPayments"
	PaymentService_CapturePayment_FullMethodName             = "/payments.v1.PaymentService/CapturePayment"
	PaymentService_RefundPayment_FullMethodName              = "/payments.v1.PaymentService/RefundPayment"
	PaymentService_VoidPayment_FullMethodName                = "/payments.v1.PaymentService/VoidPayment"
	PaymentService_ResolveUnknownAttempt_FullMethodName      = "/payments.v1.PaymentService/ResolveUnknownAttempt"
	PaymentService_MarkReconciliationRequired_FullMethodName = "/payments.v1.PaymentService/MarkReconciliationRequired"
	PaymentService_ApplyWebhookOutcome_FullMethodName        = "/payments.v1.PaymentService/ApplyWebhookOutcome"
	PaymentService_GetRoutingPlan_FullMethodName             = "/payments.v1.PaymentService/GetRoutingPlan"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Payment orchestration (BC-6). The money path.
type PaymentServiceClient interface {
	// Create, risk-assess, route and dispatch a payment. A PROCESSING or PENDING result
	// is a normal response.
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
	// Read one payment with its attempts and refunds.
	GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentResponse, error)
	// Cursor-paginated listing, including the reconciler's work queue.
	ListPayments(ctx context.Context, in *ListPaymentsRequest, opts ...grpc.CallOption) (*ListPaymentsResponse, error)
	// Capture an authorization, in full or in part.
	CapturePayment(ctx context.Context, in *CapturePaymentRequest, opts ...grpc.CallOption) (*CapturePaymentResponse, error)
	// Refund a captured payment. Available while the merchant is suspended.
	RefundPayment(ctx context.Context, in *RefundPaymentRequest, opts ...grpc.CallOption) (*RefundPaymentResponse, error)
	// Void an authorization in full. Available while the merchant is suspended.
	VoidPayment(ctx context.Context, in *VoidPaymentRequest, opts ...grpc.CallOption) (*VoidPaymentResponse, error)
	// Reconciler callback. One of the only three ways out of PROCESSING.
	ResolveUnknownAttempt(ctx context.Context, in *ResolveUnknownAttemptRequest, opts ...grpc.CallOption) (*ResolveUnknownAttemptResponse, error)
	// Park a payment for reconciliation and raise the alerting event.
	MarkReconciliationRequired(ctx context.Context, in *MarkReconciliationRequiredRequest, opts ...grpc.CallOption) (*MarkReconciliationRequiredResponse, error)
	// Apply a translated, signature-verified gateway webhook outcome.
	ApplyWebhookOutcome(ctx context.Context, in *ApplyWebhookOutcomeRequest, opts ...grpc.CallOption) (*ApplyWebhookOutcomeResponse, error)
	// Read a routing plan for incident analysis.
	GetRoutingPlan(ctx context.Context, in *GetRoutingPlanRequest, opts ...grpc.CallOption) (*GetRoutingPlanResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, PaymentService_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ListPayments(ctx context.Context, in *ListPaymentsRequest, opts ...grpc.CallOption) (*ListPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentsResponse)
	err := c.cc.Invoke(ctx, PaymentService_ListPayments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CapturePayment(ctx context.Context, in *CapturePaymentRequest, opts ...grpc.CallOption) (*CapturePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapturePaymentResponse)
	err := c.cc.Invoke(ctx, PaymentService_CapturePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) RefundPayment(ctx context.Context, in *RefundPaymentRequest, opts ...grpc.CallOption) (*RefundPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundPaymentResponse)
	err := c.cc.Invoke(ctx, PaymentService_RefundPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) VoidPayment(ctx context.Context, in *VoidPaymentRequest, opts ...grpc.CallOption) (*VoidPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoidPaymentResponse)
	err := c.cc.Invoke(ctx, PaymentService_VoidPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ResolveUnknownAttempt(ctx context.Context, in *ResolveUnknownAttemptRequest, opts ...grpc.CallOption) (*ResolveUnknownAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveUnknownAttemptResponse)
	err := c.cc.Invoke(ctx, PaymentService_ResolveUnknownAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) MarkReconciliationRequired(ctx context.Context, in *MarkReconciliationRequiredRequest, opts ...grpc.CallOption) (*MarkReconciliationRequiredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkReconciliationRequiredResponse)
	err := c.cc.Invoke(ctx, PaymentService_MarkReconciliationRequired_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ApplyWebhookOutcome(ctx context.Context, in *ApplyWebhookOutcomeRequest, opts ...grpc.CallOption) (*ApplyWebhookOutcomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyWebhookOutcomeResponse)
	err := c.cc.Invoke(ctx, PaymentService_ApplyWebhookOutcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetRoutingPlan(ctx context.Context, in *GetRoutingPlanRequest, opts ...grpc.CallOption) (*GetRoutingPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingPlanResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetRoutingPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
//
// Payment orchestration (BC-6). The money path.
type PaymentServiceServer interface {
	// Create, risk-assess, route and dispatch a payment. A PROCESSING or PENDING result
	// is a normal response.
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	// Read one payment with its attempts and refunds.
	GetPayment(context.Context, *GetPaymentRequest) (*GetPaymentResponse, error)
	// Cursor-paginated listing, including the reconciler's work queue.
	ListPayments(context.Context, *ListPaymentsRequest) (*ListPaymentsResponse, error)
	// Capture an authorization, in full or in part.
	CapturePayment(context.Context, *CapturePaymentRequest) (*CapturePaymentResponse, error)
	// Refund a captured payment. Available while the merchant is suspended.
	RefundPayment(context.Context, *RefundPaymentRequest) (*RefundPaymentResponse, error)
	// Void an authorization in full. Available while the merchant is suspended.
	VoidPayment(context.Context, *VoidPaymentRequest) (*VoidPaymentResponse, error)
	// Reconciler callback. One of the only three ways out of PROCESSING.
	ResolveUnknownAttempt(context.Context, *ResolveUnknownAttemptRequest) (*ResolveUnknownAttemptResponse, error)
	// Park a payment for reconciliation and raise the alerting event.
	MarkReconciliationRequired(context.Context, *MarkReconciliationRequiredRequest) (*MarkReconciliationRequiredResponse, error)
	// Apply a translated, signature-verified gateway webhook outcome.
	ApplyWebhookOutcome(context.Context, *ApplyWebhookOutcomeRequest) (*ApplyWebhookOutcomeResponse, error)
	// Read a routing plan for incident analysis.
	GetRoutingPlan(context.Context, *GetRoutingPlanRequest) (*GetRoutingPlanResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPaymentServiceServer) GetPayment(context.Context, *GetPaymentRequest) (*GetPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayment not implemented")
}
func (UnimplementedPaymentServiceServer) ListPayments(context.Context, *ListPaymentsRequest) (*ListPaymentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPayments not implemented")
}
func (UnimplementedPaymentServiceServer) CapturePayment(context.Context, *CapturePaymentRequest) (*CapturePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CapturePayment not implemented")
}
func (UnimplementedPaymentServiceServer) RefundPayment(context.Context, *RefundPaymentRequest) (*RefundPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundPayment not implemented")
}
func (UnimplementedPaymentServiceServer) VoidPayment(context.Context, *VoidPaymentRequest) (*VoidPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoidPayment not implemented")
}
func (UnimplementedPaymentServiceServer) ResolveUnknownAttempt(context.Context, *ResolveUnknownAttemptRequest) (*ResolveUnknownAttemptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveUnknownAttempt not implemented")
}
func (UnimplementedPaymentServiceServer) MarkReconciliationRequired(context.Context, *MarkReconciliationRequiredRequest) (*MarkReconciliationRequiredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkReconciliationRequired not implemented")
}
func (UnimplementedPaymentServiceServer) ApplyWebhookOutcome(context.Context, *ApplyWebhookOutcomeRequest) (*ApplyWebhookOutcomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyWebhookOutcome not implemented")
}
func (UnimplementedPaymentServiceServer) GetRoutingPlan(context.Context, *GetRoutingPlanRequest) (*GetRoutingPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingPlan not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPayment(ctx, req.(*GetPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ListPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ListPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ListPayments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ListPayments(ctx, req.(*ListPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CapturePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapturePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CapturePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CapturePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CapturePayment(ctx, req.(*CapturePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_RefundPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).RefundPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_RefundPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).RefundPayment(ctx, req.(*RefundPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_VoidPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).VoidPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_VoidPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).VoidPayment(ctx, req.(*VoidPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ResolveUnknownAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveUnknownAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ResolveUnknownAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ResolveUnknownAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ResolveUnknownAttempt(ctx, req.(*ResolveUnknownAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_MarkReconciliationRequired_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReconciliationRequiredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).MarkReconciliationRequired(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_MarkReconciliationRequired_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).MarkReconciliationRequired(ctx, req.(*MarkReconciliationRequiredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ApplyWebhookOutcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyWebhookOutcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ApplyWebhookOutcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ApplyWebhookOutcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ApplyWebhookOutcome(ctx, req.(*ApplyWebhookOutcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetRoutingPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetRoutingPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetRoutingPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetRoutingPlan(ctx, req.(*GetRoutingPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payments.v1.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _PaymentService_CreatePayment_Handler,
		},
		{
			MethodName: "GetPayment",
			Handler:    _PaymentService_GetPayment_Handler,
		},
		{
			MethodName: "ListPayments",
			Handler:    _PaymentService_ListPayments_Handler,
		},
		{
			MethodName: "CapturePayment",
			Handler:    _PaymentService_CapturePayment_Handler,
		},
		{
			MethodName: "RefundPayment",
			Handler:    _PaymentService_RefundPayment_Handler,
		},
		{
			MethodName: "VoidPayment",
			Handler:    _PaymentService_VoidPayment_Handler,
		},
		{
			MethodName: "ResolveUnknownAttempt",
			Handler:    _PaymentService_ResolveUnknownAttempt_Handler,
		},
		{
			MethodName: "MarkReconciliationRequired",
			Handler:    _PaymentService_MarkReconciliationRequired_Handler,
		},
		{
			MethodName: "ApplyWebhookOutcome",
			Handler:    _PaymentService_ApplyWebhookOutcome_Handler,
		},
		{
			MethodName: "GetRoutingPlan",
			Handler:    _PaymentService_GetRoutingPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payments/v1/payment.proto",
}
