package handlers

import (
	"context"
	"net/http"
	"sort"
	"strings"
	"time"

	domaingateway "github.com/udaykishore-resu/payments-platform/internal/domain/gateway"
	"github.com/udaykishore-resu/payments-platform/internal/domain/shared"
	"github.com/udaykishore-resu/payments-platform/internal/transport/httpapi"
	"github.com/udaykishore-resu/payments-platform/pkg/apierror"
)

// GatewayService is the read-only gateway catalogue plus credential rotation.
//
// Rotation is on the same interface as the catalogue reads because they share a resource — the
// merchant's connection to a gateway — and splitting them would mean two dependencies that are
// always wired together and always to the same object.
type GatewayService interface {
	Get(ctx context.Context, id shared.GatewayID) (*domaingateway.Gateway, error)
	List(ctx context.Context) ([]*domaingateway.Gateway, error)
	Health(ctx context.Context, id shared.GatewayID, ops []shared.Operation) ([]*domaingateway.Health, error)
	RotateCredentials(ctx context.Context, cmd RotateCommand) (*RotationAccepted, error)
}

// RotateCommand asks for a credential rotation.
//
// It carries no credential material in either direction — only which connection to rotate and
// why. The new secret is generated by the gateway, stored under a reference, and the reference is
// all that ever crosses a process boundary. A rotation API that accepted a secret would put that
// secret in a request body, a TLS-terminating proxy's memory, and an access log's request size.
type RotateCommand struct {
	TenantID    shared.TenantID
	GatewayID   shared.GatewayID
	MerchantID  shared.MerchantID
	Environment shared.Environment
	Reason      string
	Note        string
	ActorID     string
}

// RotationAccepted is the acknowledgement of a rotation that is now running with dual-run
// overlap: the new credential is provisioned and verified before the old one is revoked, so no
// in-flight authorization is orphaned by the change.
type RotationAccepted struct {
	ConnectionID      shared.ConnectionID
	State             string
	CredentialRef     string
	PreviousExpiresAt *time.Time
	StartedAt         time.Time
}

func registerGateways(rt *httpapi.Router, d Deps) {
	h := &gatewayHandlers{svc: d.Gateways, region: d.Region}
	rt.Handle(http.MethodGet, httpapi.RouteListGateways, "listGateways", h.list)
	rt.Handle(http.MethodGet, httpapi.RouteGetGateway, "getGateway", h.get)
	rt.Handle(http.MethodGet, httpapi.RouteGatewayHealth, "getGatewayHealth", h.health)
	rt.Handle(http.MethodPost, httpapi.RouteRotateCredentials, "rotateGatewayCredentials", h.rotate)
}

type gatewayHandlers struct {
	svc    GatewayService
	region string
}

// list implements `listGateways`.
//
// DEPRECATED gateways are still listed. Hiding them would break every client that reads the
// catalogue to render a name for a gateway an existing connection still uses; the deprecation is
// communicated by the `status` field and enforced at configuration-publish time, where naming a
// deprecated gateway as a routing primary is refused.
//
// The catalogue is platform-global and small — tens of entries — so it is filtered and paginated
// in memory rather than in the repository. That is a deliberate simplification with a bound: if
// the catalogue ever reaches the thousands, this becomes a repository query, and the cursor
// contract above it does not change.
func (h *gatewayHandlers) list(w http.ResponseWriter, r *http.Request) error {
	page, err := httpapi.DecodePage(r)
	if err != nil {
		return err
	}
	all, err := h.svc.List(r.Context())
	if err != nil {
		return err
	}
	filtered, err := filterGateways(all, r)
	if err != nil {
		return err
	}
	sort.Slice(filtered, func(i, j int) bool { return filtered[i].ID() < filtered[j].ID() })

	start := 0
	if page.Cursor != "" {
		// The cursor is the last id of the previous page. It is opaque to clients by contract
		// and happens to be readable here; that is acceptable for a global, non-tenant-scoped
		// catalogue where the identifier is already public in every response.
		for i, g := range filtered {
			if g.ID().String() == page.Cursor {
				start = i + 1
				break
			}
		}
	}
	end := min(start+page.Limit, len(filtered))
	out := make([]httpapi.Gateway, 0, end-start)
	for _, g := range filtered[start:end] {
		out = append(out, httpapi.GatewayOf(g))
	}
	next := ""
	if end < len(filtered) && end > start {
		next = filtered[end-1].ID().String()
	}
	httpapi.WriteJSON(w, r, http.StatusOK, httpapi.PageOf(out, next))
	return nil
}

func filterGateways(in []*domaingateway.Gateway, r *http.Request) ([]*domaingateway.Gateway, error) {
	q := r.URL.Query()
	wantStatus := q.Get("status")
	wantCurrency := q.Get("currency")
	wantMethod := q.Get("paymentMethod")

	out := make([]*domaingateway.Gateway, 0, len(in))
	for _, g := range in {
		if wantStatus != "" && string(g.Status()) != wantStatus {
			continue
		}
		c := g.Capabilities()
		if wantCurrency != "" && !containsString(currencyStrings(c), wantCurrency) {
			continue
		}
		if wantMethod != "" && !containsString(methodStrings(c), wantMethod) {
			continue
		}
		out = append(out, g)
	}
	return out, nil
}

func currencyStrings(c domaingateway.Capabilities) []string {
	out := make([]string, 0, len(c.Currencies))
	for _, v := range c.Currencies {
		out = append(out, string(v))
	}
	return out
}

func methodStrings(c domaingateway.Capabilities) []string {
	out := make([]string, 0, len(c.Methods))
	for _, v := range c.Methods {
		out = append(out, string(v))
	}
	return out
}

func containsString(set []string, want string) bool {
	for _, v := range set {
		if v == want {
			return true
		}
	}
	return false
}

// get implements `getGateway`.
func (h *gatewayHandlers) get(w http.ResponseWriter, r *http.Request) error {
	id, err := gatewayTarget(r)
	if err != nil {
		return err
	}
	g, err := h.svc.Get(r.Context(), id)
	if err != nil {
		return err
	}
	httpapi.SetETagRaw(w, g.APIVersion())
	httpapi.WriteJSON(w, r, http.StatusOK, httpapi.GatewayOf(g))
	return nil
}

// health implements `getGatewayHealth`.
//
// # Why this read is AP and says how stale it is
//
// Health is a measurement, and a measurement that is briefly stale is far more useful than one
// that is unavailable. The endpoint therefore serves the last snapshot rather than failing, and
// `observedAtAgeMs` states how old it is so the caller can decide. A health endpoint that returns
// 503 when the health store is slow is a health endpoint that goes dark exactly during the
// incident it exists to describe.
//
// Health is measured per (gateway, operation) and deliberately not per merchant: per-merchant
// samples are too sparse to be statistically meaningful, and a health signal computed from four
// observations is noise a routing engine would act on.
func (h *gatewayHandlers) health(w http.ResponseWriter, r *http.Request) error {
	id, err := gatewayTarget(r)
	if err != nil {
		return err
	}
	ops, err := operationsFilter(r)
	if err != nil {
		return err
	}
	region := r.URL.Query().Get("region")
	if region == "" {
		region = h.region
	}
	items, err := h.svc.Health(r.Context(), id, ops)
	if err != nil {
		return err
	}
	now := time.Now().UTC()
	report := httpapi.GatewayHealthReport{
		GatewayID:   id.String(),
		GatewayCode: id.String(),
		Region:      region,
		Operations:  make([]httpapi.GatewayHealth, 0, len(items)),
	}
	for _, hh := range items {
		report.Operations = append(report.Operations, httpapi.GatewayHealthOf(hh, region, now))
	}
	// A short cache lifetime rather than no-store: this is a measurement with no tenant data in
	// it, a dashboard polling it every second should be allowed to reuse a one-second-old copy,
	// and the freshness the caller actually needs is already stated in observedAtAgeMs.
	w.Header().Set(httpapi.HeaderCacheControl, "max-age=5")
	httpapi.WriteJSON(w, r, http.StatusOK, report)
	return nil
}

func operationsFilter(r *http.Request) ([]shared.Operation, error) {
	var out []shared.Operation
	for _, raw := range r.URL.Query()["operation"] {
		for _, part := range strings.Split(raw, ",") {
			part = strings.TrimSpace(part)
			if part == "" {
				continue
			}
			op, ok := operationOf(part)
			if !ok {
				return nil, apierror.Newf(apierror.CodeValidationFailed,
					"unknown gateway operation %q", part).
					WithDetail(apierror.Detail{
						Field: "operation", Code: "UNKNOWN_ENUM_VALUE",
						Message: "Valid operations are AUTHORIZE, CAPTURE, REFUND, VOID, LOOKUP, PROVISION.",
						RuleID:  "L1.ENUM_MEMBER",
					})
			}
			out = append(out, op)
		}
	}
	return out, nil
}

// operationOf maps the contract's uppercase operation enum onto the domain's lowercase one.
func operationOf(s string) (shared.Operation, bool) {
	switch s {
	case "AUTHORIZE":
		return shared.OpAuthorize, true
	case "CAPTURE":
		return shared.OpCapture, true
	case "REFUND":
		return shared.OpRefund, true
	case "VOID":
		return shared.OpVoid, true
	case "LOOKUP":
		return shared.OpLookup, true
	case "PROVISION":
		return shared.OpProvision, true
	}
	return "", false
}

// rotate implements `rotateGatewayCredentials`.
//
// 202, not 200: rotation runs asynchronously with a dual-run overlap, and the response is an
// acknowledgement. Holding the request open across provisioning a credential at the gateway,
// verifying it with a live L3 call, and revoking the old one would be a multi-second request on
// the control plane for an operation whose completion the caller can observe on the connection.
func (h *gatewayHandlers) rotate(w http.ResponseWriter, r *http.Request) error {
	id, err := gatewayTarget(r)
	if err != nil {
		return err
	}
	tc, err := tenantOf(r)
	if err != nil {
		return err
	}
	var req httpapi.RotateCredentialsRequest
	if err := decodeInto(r, &req); err != nil {
		return err
	}
	merchantID, err := shared.ParseMerchantID(req.MerchantID)
	if err != nil {
		return err
	}
	env, err := shared.ParseEnvironment(strings.ToLower(req.Environment))
	if err != nil {
		return err
	}
	if !isRotationReason(req.Reason) {
		return apierror.Newf(apierror.CodeValidationFailed,
			"unknown rotation reason %q", req.Reason).
			WithDetail(apierror.Detail{
				Field: "reason", Code: "UNKNOWN_ENUM_VALUE",
				Message: "Valid reasons are SCHEDULED, SUSPECTED_COMPROMISE, OPERATOR_REQUEST, GATEWAY_REQUEST.",
				RuleID:  "L1.ENUM_MEMBER",
			})
	}
	actorID := ""
	if p := httpapi.Principal(r.Context()); p != nil {
		actorID = p.ID
	}
	res, err := h.svc.RotateCredentials(r.Context(), RotateCommand{
		TenantID:    tc.TenantID,
		GatewayID:   id,
		MerchantID:  merchantID,
		Environment: env,
		Reason:      req.Reason,
		Note:        req.Note,
		ActorID:     actorID,
	})
	if err != nil {
		return err
	}
	httpapi.WriteJSON(w, r, http.StatusAccepted, httpapi.CredentialRotationAccepted{
		ConnectionID:      res.ConnectionID.String(),
		GatewayID:         id.String(),
		MerchantID:        merchantID.String(),
		Environment:       strings.ToUpper(string(env)),
		State:             res.State,
		CredentialRef:     res.CredentialRef,
		PreviousExpiresAt: res.PreviousExpiresAt,
		StartedAt:         res.StartedAt,
	})
	return nil
}

func isRotationReason(s string) bool {
	switch s {
	case "SCHEDULED", "SUSPECTED_COMPROMISE", "OPERATOR_REQUEST", "GATEWAY_REQUEST":
		return true
	}
	return false
}

func gatewayTarget(r *http.Request) (shared.GatewayID, error) {
	raw, err := pathValue(r, "gatewayId")
	if err != nil {
		return "", err
	}
	return shared.ParseGatewayID(raw)
}
