apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pp-observability
resources:
  - prometheusrule-recording.yaml
  - prometheusrule-slo-burn.yaml
  - prometheusrule-alerts.yaml
