apiVersion: v2
name: payment-api
description: The only public money-path ingress. Stateless. 99.99% availability, p99 <= 250ms.
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.28.0-0"
keywords:
  - payments
  - data-plane
annotations:
  pp.plane: data
  pp.namespace: pp-data-plane
  pp.node-group: data
  pp.availability-target: "99.99%"
dependencies:
  - name: pp-common
    version: 1.0.0
    repository: "file://../pp-common"
